### ISSUE TITLE
Selection - Query Builder - Add Query translates values to "null"

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#1]
When using the Selection Query Builder and selecting Field Names which have a domain, upon clicking the Add button, the system replaces the selected Unique Value with null.

To recreate:
1. Within Query Builder, select Field Name = County, Operator = "=", Unique Value = any county.
2. Click Add
3. The county selected becomes null in the query statement block.

**Comment by GraceAi** [comment]
Fixed. Please wait for retest.

**Comment by johnshiu** [comment]
![image](https://cloud.githubusercontent.com/assets/6249952/10628074/c9fb5494-778e-11e5-8ab1-dc670b059eeb.png)

I think this is expected behavior, as the query statement block shows the translated domain value. Please see the screenshot where Allegany County is selected, and the query block correctly shows the translated value of 01.

**Comment by leeensminger** [comment]
Is it possible the fix has been made and not pushed up?  I'm seeing different results:

![image](https://cloud.githubusercontent.com/assets/4103847/10636467/fcc03dd8-77cd-11e5-9277-4c05bb50da0b.png)

After clicking Add:
![image](https://cloud.githubusercontent.com/assets/4103847/10636474/05a5b950-77ce-11e5-8c96-e5f2af91f7ca.png)

After clicking Validate:
![image](https://cloud.githubusercontent.com/assets/4103847/10636495/1bc26576-77ce-11e5-8169-79ea08c79664.png)

**Comment by leeensminger** [comment]
Appears fixed.
