### ISSUE TITLE
Mitigation Summary grid does not display edits.

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#75]
After editing and saving the Mitigation Summary panel, edits are not displayed within the grid, and values return to zero.  This feature had previously been working as designed. 

Reproduce:
1. In Projects tab, enable editing.  Double click in the Mitigation Summary panel to open the form.
2. Enter a value for MITIGATION REQUIRED and click apply.
3. The edits are not displayed.  I cannot confirm if edits are actually being written to the database, or not.

Very likely this issue is highly correlated with #41 .

**Comment by johnshiu** [comment]
As a developer note, the JSON submitted for the edit shows a null MITIGATION_LEDGER_ID being sent to the service, which is probably why it isn't updating. No code has changed anywhere, though...

![image](https://cloud.githubusercontent.com/assets/6249952/12210633/56dbd0fe-b629-11e5-8e94-aaae39187a62.png)

**Comment by johnshiu** [comment]
This has been fixed in the widget code. Given the code structure that was already there, the simplest way for me to fix it was to have the MITIGATION_LEDGER_ID show up at the very bottom of the window (not editable). Not the prettiest, but I think changing how that's handled would require some additional restructuring of the code.
