### ISSUE TITLE
Projects tab - Project type (parent, child) is incorrectly displayed

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#78]
With the latest data refresh, there are issues with the categorization of projects.  The xml you last loaded contained three projects, 2 of which had PROJECT.PARENT_PROJ_ID = null, and therefore are parent projects.  The third project is a legitimate child project, and the PARENT_PROJ_ID references one of the other projects.  In the widget, all three projects show up as subprojects (“Type” field = SUB).  I’m pretty confident this is a data issue, but – can you confirm what the trigger is in the widget, that identifies projects as SUB (child) vs PROJ (parent)?   I tested and confirmed that creating new projects (both parent and child) in the application work as designed.

**Comment by johnshiu** [comment]
It looks like in the database, parent_project_id should be set to 0 if there is no parent project, instead of null. The new projects, HAxx1 and HA0521 have 0 set as their parent project. I'm guessing this is causing MD 24/MD 924 to not show up in other project areas as well. 

I have updated the parent_project_id to 0 for any that had nulls. This may resolve some of the project-related issues you've experienced.

**Comment by leeensminger** [comment]
Awesome - I'm providing an updated database soon, so I will make that modification.  Thanks!

**Comment by sfabijanski** [comment]
Setting the parent_project_id to zero after the record has been inserted may not properly fire some of the triggers--mitigation summary for instance ( issue #75), though I'm not sure. 

From the Projects tab the creation of a new project will include a zero when the new record is a top-level project. It might be safer, particularly since items are created outside the application, to set a default value of zero on the parent_project_id field within the database rules. That way, if a new record is entered with null, the database will automatically populate with the zero and trigger any of the items relying on the field value.
